version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snowpack
    versions:
    - 3.0.11
    - 3.0.12
    - 3.0.13
    - 3.1.2
    - 3.2.2
    - 3.3.0
    - 3.3.3
    - 3.3.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: svelte
    versions:
    - 3.32.0
    - 3.32.1
    - 3.32.2
    - 3.32.3
    - 3.34.0
    - 3.35.0
    - 3.36.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: "@snowpack/plugin-svelte"
    versions:
    - 3.5.2
    - 3.6.0
  - dependency-name: nouislider
    versions:
    - 14.6.3
    - 14.6.4
  - dependency-name: vega-embed
    versions:
    - 6.15.0
    - 6.15.1
    - 6.15.2
    - 6.16.0
  - dependency-name: "@snowpack/plugin-webpack"
    versions:
    - 2.3.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
