import y from"./uniq.js";function v(b,g,i){var d=b.length,l=g.arrayArgs.length,a=g.indexArgs.length>0,j=[],m=[],f=0,c=0,e,k;for(e=0;e<d;++e)m.push(["i",e,"=0"].join(""));for(k=0;k<l;++k)for(e=0;e<d;++e)c=f,f=b[e],e===0?m.push(["d",k,"s",e,"=t",k,"p",f].join("")):m.push(["d",k,"s",e,"=(t",k,"p",f,"-s",c,"*t",k,"p",c,")"].join(""));for(m.length>0&&j.push("var "+m.join(",")),e=d-1;e>=0;--e)f=b[e],j.push(["for(i",e,"=0;i",e,"<s",f,";++i",e,"){"].join(""));for(j.push(i),e=0;e<d;++e){for(c=f,f=b[e],k=0;k<l;++k)j.push(["p",k,"+=d",k,"s",e].join(""));a&&(e>0&&j.push(["index[",c,"]-=s",c].join("")),j.push(["++index[",f,"]"].join(""))),j.push("}")}return j.join(`
`)}function z(b,g,i,d){for(var l=g.length,a=i.arrayArgs.length,j=i.blockSize,m=i.indexArgs.length>0,f=[],c=0;c<a;++c)f.push(["var offset",c,"=p",c].join(""));for(var c=b;c<l;++c)f.push(["for(var j"+c+"=SS[",g[c],"]|0;j",c,">0;){"].join("")),f.push(["if(j",c,"<",j,"){"].join("")),f.push(["s",g[c],"=j",c].join("")),f.push(["j",c,"=0"].join("")),f.push(["}else{s",g[c],"=",j].join("")),f.push(["j",c,"-=",j,"}"].join("")),m&&f.push(["index[",g[c],"]=j",c].join(""));for(var c=0;c<a;++c){for(var e=["offset"+c],k=b;k<l;++k)e.push(["j",k,"*t",c,"p",g[k]].join(""));f.push(["p",c,"=(",e.join("+"),")"].join(""))}f.push(v(g,i,d));for(var c=b;c<l;++c)f.push("}");return f.join(`
`)}function A(b){for(var g=0,i=b[0].length;g<i;){for(var d=1;d<b.length;++d)if(b[d][g]!==b[0][g])return g;++g}return g}function t(b,g,i){for(var d=b.body,l=[],a=[],j=0;j<b.args.length;++j){var m=b.args[j];if(m.count<=0)continue;var f=new RegExp(m.name,"g"),c="",e=g.arrayArgs.indexOf(j);switch(g.argTypes[j]){case"offset":var k=g.offsetArgIndex.indexOf(j),h=g.offsetArgs[k];e=h.array,c="+q"+k;case"array":c="p"+e+c;var o="l"+j,n="a"+e;if(g.arrayBlockIndices[e]===0)m.count===1?i[e]==="generic"?m.lvalue?(l.push(["var ",o,"=",n,".get(",c,")"].join("")),d=d.replace(f,o),a.push([n,".set(",c,",",o,")"].join(""))):d=d.replace(f,[n,".get(",c,")"].join("")):d=d.replace(f,[n,"[",c,"]"].join("")):i[e]==="generic"?(l.push(["var ",o,"=",n,".get(",c,")"].join("")),d=d.replace(f,o),m.lvalue&&a.push([n,".set(",c,",",o,")"].join(""))):(l.push(["var ",o,"=",n,"[",c,"]"].join("")),d=d.replace(f,o),m.lvalue&&a.push([n,"[",c,"]=",o].join("")));else{for(var p=[m.name],r=[c],q=0;q<Math.abs(g.arrayBlockIndices[e]);q++)p.push("\\s*\\[([^\\]]+)\\]"),r.push("$"+(q+1)+"*t"+e+"b"+q);f=new RegExp(p.join(""),"g"),c=r.join("+");if(i[e]==="generic")throw new Error("cwise: Generic arrays not supported in combination with blocks!");d=d.replace(f,[n,"[",c,"]"].join(""))}break;case"scalar":d=d.replace(f,"Y"+g.scalarArgs.indexOf(j));break;case"index":d=d.replace(f,"index");break;case"shape":d=d.replace(f,"shape");break}}return[l.join(`
`),d,a.join(`
`)].join(`
`).trim()}function B(b){for(var g=new Array(b.length),i=!0,d=0;d<b.length;++d){var l=b[d],a=l.match(/\d+/);a?a=a[0]:a="",l.charAt(0)===0?g[d]="u"+l.charAt(1)+a:g[d]=l.charAt(0)+a,d>0&&(i=i&&g[d]===g[d-1])}return i?g[0]:g.join("")}function C(b,g){for(var i=g[1].length-Math.abs(b.arrayBlockIndices[0])|0,d=new Array(b.arrayArgs.length),l=new Array(b.arrayArgs.length),a=0;a<b.arrayArgs.length;++a)l[a]=g[2*a],d[a]=g[2*a+1];for(var j=[],m=[],f=[],c=[],e=[],a=0;a<b.arrayArgs.length;++a){b.arrayBlockIndices[a]<0?(f.push(0),c.push(i),j.push(i),m.push(i+b.arrayBlockIndices[a])):(f.push(b.arrayBlockIndices[a]),c.push(b.arrayBlockIndices[a]+i),j.push(0),m.push(b.arrayBlockIndices[a]));for(var k=[],h=0;h<d[a].length;h++)f[a]<=d[a][h]&&d[a][h]<c[a]&&k.push(d[a][h]-f[a]);e.push(k)}for(var o=["SS"],n=["'use strict'"],p=[],h=0;h<i;++h)p.push(["s",h,"=SS[",h,"]"].join(""));for(var a=0;a<b.arrayArgs.length;++a){o.push("a"+a),o.push("t"+a),o.push("p"+a);for(var h=0;h<i;++h)p.push(["t",a,"p",h,"=t",a,"[",f[a]+h,"]"].join(""));for(var h=0;h<Math.abs(b.arrayBlockIndices[a]);++h)p.push(["t",a,"b",h,"=t",a,"[",j[a]+h,"]"].join(""))}for(var a=0;a<b.scalarArgs.length;++a)o.push("Y"+a);b.shapeArgs.length>0&&p.push("shape=SS.slice(0)");if(b.indexArgs.length>0){for(var r=new Array(i),a=0;a<i;++a)r[a]="0";p.push(["index=[",r.join(","),"]"].join(""))}for(var a=0;a<b.offsetArgs.length;++a){for(var q=b.offsetArgs[a],s=[],h=0;h<q.offset.length;++h){if(q.offset[h]===0)continue;q.offset[h]===1?s.push(["t",q.array,"p",h].join("")):s.push([q.offset[h],"*t",q.array,"p",h].join(""))}s.length===0?p.push("q"+a+"=0"):p.push(["q",a,"=",s.join("+")].join(""))}var D=y([].concat(b.pre.thisVars).concat(b.body.thisVars).concat(b.post.thisVars));p=p.concat(D),p.length>0&&n.push("var "+p.join(","));for(var a=0;a<b.arrayArgs.length;++a)n.push("p"+a+"|=0");b.pre.body.length>3&&n.push(t(b.pre,b,l));var w=t(b.body,b,l),u=A(e);u<i?n.push(z(u,e[0],b,w)):n.push(v(e[0],b,w)),b.post.body.length>3&&n.push(t(b.post,b,l)),b.debug&&console.log("-----Generated cwise routine for ",g,`:
`+n.join(`
`)+`
----------`);var x=[b.funcName||"unnamed","_cwise_loop_",d[0].join("s"),"m",u,B(l)].join(""),E=new Function(["function ",x,"(",o.join(","),"){",n.join(`
`),"} return ",x].join(""));return E()}export default C;
