import I from"./uniq.js";function A(s,o,h){var n=s.length,d=o.arrayArgs.length,e=o.indexArgs.length>0,l=[],f=[],t=0,a=0,i,u;for(i=0;i<n;++i)f.push(["i",i,"=0"].join(""));for(u=0;u<d;++u)for(i=0;i<n;++i)a=t,t=s[i],i===0?f.push(["d",u,"s",i,"=t",u,"p",t].join("")):f.push(["d",u,"s",i,"=(t",u,"p",t,"-s",a,"*t",u,"p",a,")"].join(""));for(f.length>0&&l.push("var "+f.join(",")),i=n-1;i>=0;--i)t=s[i],l.push(["for(i",i,"=0;i",i,"<s",t,";++i",i,"){"].join(""));for(l.push(h),i=0;i<n;++i){for(a=t,t=s[i],u=0;u<d;++u)l.push(["p",u,"+=d",u,"s",i].join(""));e&&(i>0&&l.push(["index[",a,"]-=s",a].join("")),l.push(["++index[",t,"]"].join(""))),l.push("}")}return l.join(`
`)}function T(s,o,h,n){for(var d=o.length,e=h.arrayArgs.length,l=h.blockSize,f=h.indexArgs.length>0,t=[],a=0;a<e;++a)t.push(["var offset",a,"=p",a].join(""));for(var a=s;a<d;++a)t.push(["for(var j"+a+"=SS[",o[a],"]|0;j",a,">0;){"].join("")),t.push(["if(j",a,"<",l,"){"].join("")),t.push(["s",o[a],"=j",a].join("")),t.push(["j",a,"=0"].join("")),t.push(["}else{s",o[a],"=",l].join("")),t.push(["j",a,"-=",l,"}"].join("")),f&&t.push(["index[",o[a],"]=j",a].join(""));for(var a=0;a<e;++a){for(var i=["offset"+a],u=s;u<d;++u)i.push(["j",u,"*t",a,"p",o[u]].join(""));t.push(["p",a,"=(",i.join("+"),")"].join(""))}t.push(A(o,h,n));for(var a=s;a<d;++a)t.push("}");return t.join(`
`)}function B(s){for(var o=0,h=s[0].length;o<h;){for(var n=1;n<s.length;++n)if(s[n][o]!==s[0][o])return o;++o}return o}function j(s,o,h){for(var n=s.body,d=[],e=[],l=0;l<s.args.length;++l){var f=s.args[l];if(f.count<=0)continue;var t=new RegExp(f.name,"g"),a="",i=o.arrayArgs.indexOf(l);switch(o.argTypes[l]){case"offset":var u=o.offsetArgIndex.indexOf(l),r=o.offsetArgs[u];i=r.array,a="+q"+u;case"array":a="p"+i+a;var p="l"+l,c="a"+i;if(o.arrayBlockIndices[i]===0)f.count===1?h[i]==="generic"?f.lvalue?(d.push(["var ",p,"=",c,".get(",a,")"].join("")),n=n.replace(t,p),e.push([c,".set(",a,",",p,")"].join(""))):n=n.replace(t,[c,".get(",a,")"].join("")):n=n.replace(t,[c,"[",a,"]"].join("")):h[i]==="generic"?(d.push(["var ",p,"=",c,".get(",a,")"].join("")),n=n.replace(t,p),f.lvalue&&e.push([c,".set(",a,",",p,")"].join(""))):(d.push(["var ",p,"=",c,"[",a,"]"].join("")),n=n.replace(t,p),f.lvalue&&e.push([c,"[",a,"]=",p].join("")));else{for(var g=[f.name],y=[a],v=0;v<Math.abs(o.arrayBlockIndices[i]);v++)g.push("\\s*\\[([^\\]]+)\\]"),y.push("$"+(v+1)+"*t"+i+"b"+v);if(t=new RegExp(g.join(""),"g"),a=y.join("+"),h[i]==="generic")throw new Error("cwise: Generic arrays not supported in combination with blocks!");n=n.replace(t,[c,"[",a,"]"].join(""))}break;case"scalar":n=n.replace(t,"Y"+o.scalarArgs.indexOf(l));break;case"index":n=n.replace(t,"index");break;case"shape":n=n.replace(t,"shape");break}}return[d.join(`
`),n,e.join(`
`)].join(`
`).trim()}function z(s){for(var o=new Array(s.length),h=!0,n=0;n<s.length;++n){var d=s[n],e=d.match(/\d+/);e?e=e[0]:e="",d.charAt(0)===0?o[n]="u"+d.charAt(1)+e:o[n]=d.charAt(0)+e,n>0&&(h=h&&o[n]===o[n-1])}return h?o[0]:o.join("")}function E(s,o){for(var h=o[1].length-Math.abs(s.arrayBlockIndices[0])|0,n=new Array(s.arrayArgs.length),d=new Array(s.arrayArgs.length),e=0;e<s.arrayArgs.length;++e)d[e]=o[2*e],n[e]=o[2*e+1];for(var l=[],f=[],t=[],a=[],i=[],e=0;e<s.arrayArgs.length;++e){s.arrayBlockIndices[e]<0?(t.push(0),a.push(h),l.push(h),f.push(h+s.arrayBlockIndices[e])):(t.push(s.arrayBlockIndices[e]),a.push(s.arrayBlockIndices[e]+h),l.push(0),f.push(s.arrayBlockIndices[e]));for(var u=[],r=0;r<n[e].length;r++)t[e]<=n[e][r]&&n[e][r]<a[e]&&u.push(n[e][r]-t[e]);i.push(u)}for(var p=["SS"],c=["'use strict'"],g=[],r=0;r<h;++r)g.push(["s",r,"=SS[",r,"]"].join(""));for(var e=0;e<s.arrayArgs.length;++e){p.push("a"+e),p.push("t"+e),p.push("p"+e);for(var r=0;r<h;++r)g.push(["t",e,"p",r,"=t",e,"[",t[e]+r,"]"].join(""));for(var r=0;r<Math.abs(s.arrayBlockIndices[e]);++r)g.push(["t",e,"b",r,"=t",e,"[",l[e]+r,"]"].join(""))}for(var e=0;e<s.scalarArgs.length;++e)p.push("Y"+e);if(s.shapeArgs.length>0&&g.push("shape=SS.slice(0)"),s.indexArgs.length>0){for(var y=new Array(h),e=0;e<h;++e)y[e]="0";g.push(["index=[",y.join(","),"]"].join(""))}for(var e=0;e<s.offsetArgs.length;++e){for(var v=s.offsetArgs[e],m=[],r=0;r<v.offset.length;++r){if(v.offset[r]===0)continue;v.offset[r]===1?m.push(["t",v.array,"p",r].join("")):m.push([v.offset[r],"*t",v.array,"p",r].join(""))}m.length===0?g.push("q"+e+"=0"):g.push(["q",e,"=",m.join("+")].join(""))}var x=I([].concat(s.pre.thisVars).concat(s.body.thisVars).concat(s.post.thisVars));g=g.concat(x),g.length>0&&c.push("var "+g.join(","));for(var e=0;e<s.arrayArgs.length;++e)c.push("p"+e+"|=0");s.pre.body.length>3&&c.push(j(s.pre,s,d));var w=j(s.body,s,d),b=B(i);b<h?c.push(T(b,i[0],s,w)):c.push(A(i[0],s,w)),s.post.body.length>3&&c.push(j(s.post,s,d)),s.debug&&console.log("-----Generated cwise routine for ",o,`:
`+c.join(`
`)+`
----------`);var k=[s.funcName||"unnamed","_cwise_loop_",n[0].join("s"),"m",b,z(d)].join(""),O=new Function(["function ",k,"(",p.join(","),"){",c.join(`
`),"} return ",k].join(""));return O()}export default E;
