import A from"./uniq.js";function I(s,h,u){var a=s.length,f=h.arrayArgs.length,e=h.indexArgs.length>0,d=[],p=[],t=0,n=0,o,r;for(o=0;o<a;++o)p.push(["i",o,"=0"].join(""));for(r=0;r<f;++r)for(o=0;o<a;++o)n=t,t=s[o],o===0?p.push(["d",r,"s",o,"=t",r,"p",t].join("")):p.push(["d",r,"s",o,"=(t",r,"p",t,"-s",n,"*t",r,"p",n,")"].join(""));for(p.length>0&&d.push("var "+p.join(",")),o=a-1;o>=0;--o)t=s[o],d.push(["for(i",o,"=0;i",o,"<s",t,";++i",o,"){"].join(""));for(d.push(u),o=0;o<a;++o){for(n=t,t=s[o],r=0;r<f;++r)d.push(["p",r,"+=d",r,"s",o].join(""));e&&(o>0&&d.push(["index[",n,"]-=s",n].join("")),d.push(["++index[",t,"]"].join(""))),d.push("}")}return d.join(`
`)}function z(s,h,u,a){for(var f=h.length,e=u.arrayArgs.length,d=u.blockSize,p=u.indexArgs.length>0,t=[],n=0;n<e;++n)t.push(["var offset",n,"=p",n].join(""));for(var n=s;n<f;++n)t.push(["for(var j"+n+"=SS[",h[n],"]|0;j",n,">0;){"].join("")),t.push(["if(j",n,"<",d,"){"].join("")),t.push(["s",h[n],"=j",n].join("")),t.push(["j",n,"=0"].join("")),t.push(["}else{s",h[n],"=",d].join("")),t.push(["j",n,"-=",d,"}"].join("")),p&&t.push(["index[",h[n],"]=j",n].join(""));for(var n=0;n<e;++n){for(var o=["offset"+n],r=s;r<f;++r)o.push(["j",r,"*t",n,"p",h[r]].join(""));t.push(["p",n,"=(",o.join("+"),")"].join(""))}t.push(I(h,u,a));for(var n=s;n<f;++n)t.push("}");return t.join(`
`)}function E(s){for(var h=0,u=s[0].length;h<u;){for(var a=1;a<s.length;++a)if(s[a][h]!==s[0][h])return h;++h}return h}function k(s,h,u){for(var a=s.body,f=[],e=[],d=0;d<s.args.length;++d){var p=s.args[d];if(p.count<=0)continue;var t=new RegExp(p.name,"g"),n="",o=h.arrayArgs.indexOf(d);switch(h.argTypes[d]){case"offset":var r=h.offsetArgIndex.indexOf(d),l=h.offsetArgs[r];o=l.array,n="+q"+r;case"array":n="p"+o+n;var v="l"+d,c="a"+o;if(h.arrayBlockIndices[o]===0)p.count===1?u[o]==="generic"?p.lvalue?(f.push(["var ",v,"=",c,".get(",n,")"].join("")),a=a.replace(t,v),e.push([c,".set(",n,",",v,")"].join(""))):a=a.replace(t,[c,".get(",n,")"].join("")):a=a.replace(t,[c,"[",n,"]"].join("")):u[o]==="generic"?(f.push(["var ",v,"=",c,".get(",n,")"].join("")),a=a.replace(t,v),p.lvalue&&e.push([c,".set(",n,",",v,")"].join(""))):(f.push(["var ",v,"=",c,"[",n,"]"].join("")),a=a.replace(t,v),p.lvalue&&e.push([c,"[",n,"]=",v].join("")));else{for(var y=[p.name],m=[n],g=0;g<Math.abs(h.arrayBlockIndices[o]);g++)y.push("\\s*\\[([^\\]]+)\\]"),m.push("$"+(g+1)+"*t"+o+"b"+g);if(t=new RegExp(y.join(""),"g"),n=m.join("+"),u[o]==="generic")throw new Error("cwise: Generic arrays not supported in combination with blocks!");a=a.replace(t,[c,"[",n,"]"].join(""))}break;case"scalar":a=a.replace(t,"Y"+h.scalarArgs.indexOf(d));break;case"index":a=a.replace(t,"index");break;case"shape":a=a.replace(t,"shape");break}}return[f.join(`
`),a,e.join(`
`)].join(`
`).trim()}function q(s){for(var h=new Array(s.length),u=!0,a=0;a<s.length;++a){var f=s[a],e=f.match(/\d+/);e?e=e[0]:e="",f.charAt(0)===0?h[a]="u"+f.charAt(1)+e:h[a]=f.charAt(0)+e,a>0&&(u=u&&h[a]===h[a-1])}return u?h[0]:h.join("")}function C(s,h){for(var u=h[1].length-Math.abs(s.arrayBlockIndices[0])|0,a=new Array(s.arrayArgs.length),f=new Array(s.arrayArgs.length),e=0;e<s.arrayArgs.length;++e)f[e]=h[2*e],a[e]=h[2*e+1];for(var d=[],p=[],t=[],n=[],o=[],e=0;e<s.arrayArgs.length;++e){s.arrayBlockIndices[e]<0?(t.push(0),n.push(u),d.push(u),p.push(u+s.arrayBlockIndices[e])):(t.push(s.arrayBlockIndices[e]),n.push(s.arrayBlockIndices[e]+u),d.push(0),p.push(s.arrayBlockIndices[e]));for(var r=[],l=0;l<a[e].length;l++)t[e]<=a[e][l]&&a[e][l]<n[e]&&r.push(a[e][l]-t[e]);o.push(r)}for(var v=["SS"],c=["'use strict'"],y=[],l=0;l<u;++l)y.push(["s",l,"=SS[",l,"]"].join(""));for(var e=0;e<s.arrayArgs.length;++e){v.push("a"+e),v.push("t"+e),v.push("p"+e);for(var l=0;l<u;++l)y.push(["t",e,"p",l,"=t",e,"[",t[e]+l,"]"].join(""));for(var l=0;l<Math.abs(s.arrayBlockIndices[e]);++l)y.push(["t",e,"b",l,"=t",e,"[",d[e]+l,"]"].join(""))}for(var e=0;e<s.scalarArgs.length;++e)v.push("Y"+e);if(s.shapeArgs.length>0&&y.push("shape=SS.slice(0)"),s.indexArgs.length>0){for(var m=new Array(u),e=0;e<u;++e)m[e]="0";y.push(["index=[",m.join(","),"]"].join(""))}for(var e=0;e<s.offsetArgs.length;++e){for(var g=s.offsetArgs[e],b=[],l=0;l<g.offset.length;++l){if(g.offset[l]===0)continue;g.offset[l]===1?b.push(["t",g.array,"p",l].join("")):b.push([g.offset[l],"*t",g.array,"p",l].join(""))}b.length===0?y.push("q"+e+"=0"):y.push(["q",e,"=",b.join("+")].join(""))}var T=A([].concat(s.pre.thisVars).concat(s.body.thisVars).concat(s.post.thisVars));y=y.concat(T),y.length>0&&c.push("var "+y.join(","));for(var e=0;e<s.arrayArgs.length;++e)c.push("p"+e+"|=0");s.pre.body.length>3&&c.push(k(s.pre,s,f));var O=k(s.body,s,f),w=E(o);w<u?c.push(z(w,o[0],s,O)):c.push(I(o[0],s,O)),s.post.body.length>3&&c.push(k(s.post,s,f)),s.debug&&console.log("-----Generated cwise routine for ",h,`:
`+c.join(`
`)+`
----------`);var x=[s.funcName||"unnamed","_cwise_loop_",a[0].join("s"),"m",w,q(f)].join(""),B=new Function(["function ",x,"(",v.join(","),"){",c.join(`
`),"} return ",x].join(""));return B()}export default C;
