// [snowpack] add styles to the page (skip if no document exists)
if (typeof document !== 'undefined') {
  const code = ".noUi-target,.noUi-target *{-webkit-touch-callout:none;-webkit-tap-highlight-color:rgba(0, 0, 0, 0);-webkit-user-select:none;-ms-touch-action:none;touch-action:none;-ms-user-select:none;-moz-user-select:none;user-select:none;-moz-box-sizing:border-box;box-sizing:border-box}.noUi-target{position:relative}.noUi-base,.noUi-connects{width:100%;height:100%;position:relative;z-index:1}.noUi-connects{overflow:hidden;z-index:0}.noUi-connect,.noUi-origin{will-change:transform;position:absolute;z-index:1;top:0;right:0;-ms-transform-origin:0 0;-webkit-transform-origin:0 0;-webkit-transform-style:preserve-3d;transform-origin:0 0;transform-style:flat}.noUi-connect{height:100%;width:100%}.noUi-origin{height:10%;width:10%}.noUi-horizontal .noUi-origin{height:0}.noUi-handle{-webkit-backface-visibility:hidden;backface-visibility:hidden;position:absolute}.noUi-touch-area{height:100%;width:100%}.noUi-state-tap .noUi-connect,.noUi-state-tap .noUi-origin{-webkit-transition:transform 0.3s;transition:transform 0.3s}.noUi-state-drag *{cursor:inherit !important}.noUi-horizontal{height:5px}.noUi-horizontal .noUi-handle{width:19px;height:19px;right:-8px;top:-8px;border-radius:50px}.noUi-txt-dir-rtl.noUi-horizontal .noUi-handle{left:-17px;right:auto}.noUi-target{background:#D5D5DE;border-radius:4px}.noUi-connect{background:#F79636}.noUi-target[disabled] .noUi-connect{background:#D5D5DE}.noUi-draggable{cursor:ew-resize}.noUi-handle{border-radius:3px;background:#D35C08;cursor:default;outline:0}.noUi-target[disabled] .noUi-handle{background:#D5D5DE}.noUi-active{background:#F79636}.noUi-active:focus{outline:0}.noUi-handle:after{left:17px}.noUi-tooltip{display:block;position:absolute;color:#D35C08;padding:0;text-align:center;white-space:nowrap}.noUi-target[disabled] .noUi-tooltip{color:#D5D5DE}.noUi-horizontal .noUi-tooltip{-webkit-transform:translate(-50%, 0);transform:translate(-50%, 0);left:50%;bottom:100%}.noUi-horizontal .noUi-origin > .noUi-tooltip{-webkit-transform:translate(50%, 0);transform:translate(50%, 0);left:auto;bottom:10px}";

  const styleEl = document.createElement("style");
  const codeEl = document.createTextNode(code);
  styleEl.type = 'text/css';

  styleEl.appendChild(codeEl);
  document.head.appendChild(styleEl);
}